# Side-car CI/CD script to ensure that the rename script works.
name: CI-Build

on:
    push:
        branches:
            - main
            - feature/*
            - dependabot/*

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        name: Test rename script
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

            - name: Setup uv
              uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
              with:
                  enable-cache: true

            - name: Setup Python
              run: uv python install 3.14

            - name: Run rename
              run: ./rename_template.sh mymod

            - name: Run basic build process
              run: make
