name: CI

on:
    push:
        branches:
            - main
            - feature/*

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                # https://www.python.org/downloads/
                python-version: [
                        "3.10", # EOL: 2026-10
                        "3.11", # EOL: 2027-10
                        "3.12", # EOL: 2028-10
                        "3.13", # EOL: 2029-10
                        "3.14", # EOL: 2030-10
                    ]
        name: ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v6

            - name: Setup uv
              uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: true

            - name: Setup Python ${{ matrix.python-version }}
              run: uv python install ${{ matrix.python-version }}

            - name: CI checks
              run: make

            - name: Dependency vulnerability scan
              run: make audit
