# Side-car CI/CD script to ensure that the rename script works.
name: CI-Build

on:
    push:
        branches:
            - main
            - feature/*
            - dependabot/*

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        name: Test rename script
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

            - name: Setup uv
              uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
              with:
                  enable-cache: true

            - name: Setup Python
              run: uv python install 3.14

            - name: Run rename
              run: ./rename_template.sh mymod

            - name: Run basic build process
              run: make
